"""app.db 包：按领域拆分；重导出全部公共 API 以兼容 `from app.db import X`。"""
from app.db._core import *  # noqa: F401,F403
from app.db.ops import *  # noqa: F401,F403
from app.db.analytics import *  # noqa: F401,F403
from app.db.moderation import *  # noqa: F401,F403
from app.db.admin import *  # noqa: F401,F403
from app.db.billing import *  # noqa: F401,F403
from app.db.product_memberships import *  # noqa: F401,F403
from app.db.accounts import *  # noqa: F401,F403
from app.products.zhaoxi.infrastructure.persistence.companion_world import *  # noqa: F401,F403
from app.products.zhaoxi.infrastructure.persistence.companion_world_lifecycle import *  # noqa: F401,F403
from app.products.zhaoxi.infrastructure.persistence.companion_world_mailbox import *  # noqa: F401,F403
from app.products.zhaoxi.infrastructure.persistence.companion_world_visits import *  # noqa: F401,F403
from app.products.zhaoxi.infrastructure.persistence.companion_world_human_chat import *  # noqa: F401,F403
from app.db.notifications import *  # noqa: F401,F403
from app.db.proactive import *  # noqa: F401,F403
from app.db.lifecycle import *  # noqa: F401,F403
from app.db.llm_config import *  # noqa: F401,F403
from app.db.user_meta import *  # noqa: F401,F403
from app.db.mission import *  # noqa: F401,F403
from app.db.campaign import *  # noqa: F401,F403
from app.db.campaign_analytics import *  # noqa: F401,F403
