"""鸣蝉固定文案与用户错误消息的语言解析。"""
from __future__ import annotations

import re
from typing import Any, Dict, Optional

from app.bootstrap.product_registry import (
    PRODUCTION_PRODUCT_REGISTRY,
    MINGCHAN_APP_ID,
)

_MACHINE_CODE_RE = re.compile(r"^[a-z][a-z0-9_]{1,127}$")

_MESSAGES = {
    "zh-CN": {
        "generic_error": "操作失败，请稍后重试。",
        "invalid_request": "请求内容无效，请检查后重试。",
        "not_authenticated": "请先登录后再继续。",
        "session_expired": "登录已过期，请重新验证。",
        "not_found": "未找到相关内容，可能已被删除或失效。",
        "rate_limited": "操作过于频繁，请稍后重试。",
        "service_unavailable": "服务暂时不可用，请稍后重试。",
        "account_disabled": "当前账号已停用，暂时无法继续使用。",
        "account_not_ready": "账号尚未准备完成，请稍后重试。",
        "invalid_phone": "请输入有效的中国大陆手机号码。",
        "captcha_failed": "验证码校验未通过，请重试。",
        "sms_rate_limited": "短信发送过于频繁，请稍后重试。",
        "sms_send_failed": "短信发送失败，请稍后重试。",
        "otp_not_found_or_expired": "验证码不存在或已过期，请重新获取。",
        "otp_attempts_exceeded": "尝试次数过多，请重新获取验证码。",
        "otp_invalid": "验证码错误，请检查后重试。",
        "verification_token_invalid": "验证凭证无效或已过期，请重新验证。",
        "profile_update_empty": "请至少修改一项个人资料。",
        "display_name_invalid": "昵称格式无效，请修改后重试。",
        "avatar_key_invalid": "头像选项无效，请重新选择。",
        "content_rejected": "提交的内容未通过安全检查，请修改后重试。",
        "content_review_unavailable": "内容审核服务暂时不可用，请稍后重试。",
        "deletion_not_confirmed": "请确认后再执行账号注销。",
        "reason_code_invalid": "注销原因选项无效，请重新选择。",
        "turn_in_progress": "上一条消息仍在处理中，请稍后再试。",
        "audio_too_long": "语音时长超过限制，请缩短后重试。",
        "unsupported_audio_type": "暂不支持这种语音格式，请更换格式后重试。",
        "empty_audio": "没有读取到语音内容，请重新录制。",
        "audio_too_large": "语音文件超过大小限制，请缩短后重试。",
        "asr_not_configured": "语音识别服务暂未配置，请稍后重试或改用文字。",
        "asr_provider_failed": "语音识别失败，请稍后重试或改用文字。",
        "binding_failed": "微信绑定失败，请刷新后重试。",
        "binding_gateway_unavailable": "微信绑定服务暂时不可用，请稍后重试。",
        "binding_qr_unavailable": "暂时无法生成绑定二维码，请稍后重试。",
        "binding_already_connected": "该微信已连接，请先解除原连接后再试。",
        "binding_intent_not_found": "绑定任务不存在或已过期，请重新发起绑定。",
        "wallet_not_found": "暂时无法读取账户信息，请稍后重试。",
        "creator_role_template_wrong_app": "当前产品不支持此角色模板操作。",
        "creator_role_templates_disabled": "角色模板功能暂时不可用，请稍后重试。",
        "creator_role_template_not_found": "角色模板不存在或已被删除。",
        "creator_role_template_not_eligible": "当前账号暂不具备创建角色模板的资格。",
        "creator_role_template_limit_reached": "最多可以拥有 3 个有效模板。",
        "creator_role_template_state_conflict": "模板状态已发生变化，请刷新后重试。",
        "creator_role_template_disabled_by_admin": "该模板已由平台停用，暂时无法操作。",
        "creator_role_template_expired": "该模板已过期，无法继续操作。",
        "creator_role_template_no_changes": "模板内容没有变化，无需重复提交。",
        "creator_role_template_version_not_found": "模板版本不存在，请刷新后重试。",
        "creator_role_template_version_not_approved": "只有审核通过的版本才能发布。",
        "role_review_in_progress": "模板正在审核中，请稍后查看结果。",
        "role_review_pending": "模板正在等待审核，请稍后重试。",
        "role_review_not_pending": "当前版本不在等待审核状态，请刷新后重试。",
        "role_review_unavailable": "审核服务暂时不可用，请稍后重试。",
        "ai_name_length_invalid": "角色姓名长度不符合要求，请修改后重试。",
        "ai_name_must_be_single_line": "角色姓名只能填写一行。",
        "ai_name_contains_control_characters": "角色姓名包含不支持的字符，请修改后重试。",
        "personality_text_length_invalid": "性格与底色内容长度不符合要求，请修改后重试。",
        "personality_text_contains_control_characters": "性格与底色包含不支持的字符，请修改后重试。",
        "mission_text_length_invalid": "使命内容长度不符合要求，请修改后重试。",
        "mission_text_contains_control_characters": "使命内容包含不支持的字符，请修改后重试。",
        "opening_line_length_invalid": "开场白长度不符合要求，请修改后重试。",
        "opening_line_contains_control_characters": "开场白包含不支持的字符，请修改后重试。",
        "public_summary_length_invalid": "一句话简介长度不符合要求，请修改后重试。",
        "public_summary_must_be_single_line": "一句话简介只能填写一行。",
        "public_summary_contains_control_characters": "一句话简介包含不支持的字符，请修改后重试。",
        "public_summary_must_include_ai_name": "一句话简介必须包含角色姓名。",
        "creator_role_template_summary_edit_unavailable": "当前版本的一句话简介已不能再次修改。",
        "creator_role_template_summary_review_in_progress": "一句话简介正在审核中，请稍后刷新。",
        "creator_role_template_summary_review_unavailable": "简介审核服务暂时不可用，本次未消耗修改机会，请稍后重试。",
        "creator_role_template_summary_rejected": "你修改的简介未通过审核，原简介已保留。",
        "stats_range_invalid": "统计日期范围无效，请调整后重试。",
        "faq_message_not_found": "留言不存在或已被删除。",
        "role_template_unavailable": "角色模板暂时不可用，注册时系统会重新校验。",
        "otp_code_required": "请输入验证码。",
        "invite_code_invalid": "邀请码不可用。",
        "invite_code_check_failed": "邀请码校验失败，请稍后重试。",
        "phone_verification_required": "请先完成手机号验证。",
        "binding_expired": "二维码已过期，请重新验证。",
        "copy_failed": "复制失败，请手动选择文本复制。",
        "invite_information_loading": "邀请信息还在加载，请稍后再试。",
        "invite_code_unavailable": "暂时无法获取邀请码，请刷新后重试。",
        "role_fields_required": "姓名、性格/底色、使命和开场白都必须填写。",
        "rate_limit_daily": "今天聊得有点多了，我晚些时候再继续陪你。",
        "rate_limit_rpm": "消息来得太快了，稍等一下再发我吧。",
        "generation_error": "我这边刚刚有点卡住了，你可以稍后再发我一次。",
        "moderation_outbound_blocked": "这条内容我不能继续发送，我们换个安全的话题吧。",
        "moderation_inbound_blocked": "这个话题我不太方便继续，我们换个轻松点的聊聊吧～",
        "image_understanding_failed": "这张图我没太看清，你可以说说它，或者再发我一次～",
        "voice_understanding_failed": "这段语音我没听清，你可以打字告诉我，或者再发一次～",
        "session_reset": "已重置当前会话。",
        "onboarding_welcome": "你好，很高兴能成为微信好友，你希望我怎么称呼你？",
        "app_auth_welcome": "你好，我是{name}。想聊聊此刻的心情，还是随便说点什么？",
        "tool_policy_required": "当前工具配置不完整，暂时无法执行。",
        "tool_policy_scope_mismatch": "当前工具与产品不匹配，暂时无法执行。",
        "tool_unknown": "暂不支持这个工具。",
        "tool_not_allowed": "当前产品不允许使用这个工具。",
        "tool_disabled": "这个工具当前未开启。",
        "tool_execution_failed": "工具执行失败，请稍后重试。",
        "commitment_text_required": "跟进内容不能为空。",
        "commitment_account_unavailable": "账号当前不可用，无法记录跟进。",
        "commitment_due_at_invalid": "跟进时间必须是未来时间。",
        "commitment_due_at_too_far": "跟进时间超出允许范围。",
        "reminder_fulfillment_invalid": "提醒类型无效，请重新设置。",
        "reminder_text_required": "提醒内容不能为空。",
        "reminder_time_invalid": "提醒时间格式无效，请重新设置。",
        "reminder_recurrence_invalid": "提醒周期规则无效，请重新设置。",
        "reminder_route_missing": "当前没有可用的发送目标，无法创建提醒。",
        "dynamic_reminder_unavailable": "例行简报功能当前未开放。",
        "dynamic_reminder_limit_reached": "例行简报数量已达上限，请先取消一个再新建。",
        "reminder_id_required": "缺少提醒标识，无法继续操作。",
        "reminder_not_found": "提醒不存在或无权操作。",
        "reminder_state_invalid": "当前提醒状态不支持此操作。",
        "reminder_update_empty": "没有提供需要修改的提醒内容。",
        "reminder_update_failed": "提醒更新失败，请稍后重试。",
        "content_topic_required": "内容主题不能为空。",
        "invitation_text_required": "邀请内容不能为空。",
        "invitation_url_forbidden": "主动邀请内容不能包含链接。",
        "invitation_titles_insufficient": "至少需要 3 条标题。",
        "invitation_not_found": "内容邀请不存在或无权操作。",
        "invitation_state_invalid": "当前内容邀请状态不支持此操作。",
        "invitation_expired": "内容邀请已过期。",
        "invitation_update_failed": "内容邀请更新失败，请稍后重试。",
        "feedback_type_invalid": "反馈类型无效。",
        "proactive_fields_unsupported": "包含不支持的主动消息设置字段。",
        "proactive_update_empty": "没有提供需要修改的主动消息设置。",
        "proactive_settings_invalid": "主动消息设置无效，请检查后重试。",
        "mission_not_assigned": "当前尚未分配使命。",
        "mission_content_required": "使命内容不能为空。",
    },
    "en-US": {
        "generic_error": "Something went wrong. Please try again later.",
        "invalid_request": "The request is invalid. Check it and try again.",
        "not_authenticated": "Please sign in to continue.",
        "session_expired": "Your session has expired. Please verify your account again.",
        "not_found": "This content could not be found or is no longer available.",
        "rate_limited": "Too many attempts. Please try again later.",
        "service_unavailable": "The service is temporarily unavailable. Please try again later.",
        "account_disabled": "This account is disabled and cannot be used right now.",
        "account_not_ready": "Your account is not ready yet. Please try again later.",
        "invalid_phone": "Enter a valid mainland China mobile number.",
        "captcha_failed": "Captcha verification failed. Please try again.",
        "sms_rate_limited": "SMS requests are too frequent. Please try again later.",
        "sms_send_failed": "The verification message could not be sent. Please try again later.",
        "otp_not_found_or_expired": "The verification code is missing or expired. Request a new one.",
        "otp_attempts_exceeded": "Too many attempts. Request a new verification code.",
        "otp_invalid": "The verification code is incorrect. Check it and try again.",
        "verification_token_invalid": "The verification credential is invalid or expired. Please verify again.",
        "profile_update_empty": "Change at least one profile field.",
        "display_name_invalid": "The display name is invalid. Revise it and try again.",
        "avatar_key_invalid": "The selected avatar is invalid. Choose another one.",
        "content_rejected": "The submitted content did not pass the safety check. Revise it and try again.",
        "content_review_unavailable": "Content review is temporarily unavailable. Please try again later.",
        "deletion_not_confirmed": "Confirm the request before deleting the account.",
        "reason_code_invalid": "The deletion reason is invalid. Select another option.",
        "turn_in_progress": "Your previous message is still being processed. Please wait and try again.",
        "audio_too_long": "The voice message is too long. Shorten it and try again.",
        "unsupported_audio_type": "This audio format is not supported. Use a different format.",
        "empty_audio": "No audio was received. Please record it again.",
        "audio_too_large": "The audio file is too large. Shorten it and try again.",
        "asr_not_configured": "Speech recognition is unavailable. Please try later or use text.",
        "asr_provider_failed": "Speech recognition failed. Please try later or use text.",
        "binding_failed": "WeChat binding failed. Refresh the page and try again.",
        "binding_gateway_unavailable": "WeChat binding is temporarily unavailable. Please try again later.",
        "binding_qr_unavailable": "A binding QR code could not be created. Please try again later.",
        "binding_already_connected": "This WeChat account is already connected. Disconnect it before trying again.",
        "binding_intent_not_found": "The binding request is missing or expired. Start a new binding request.",
        "wallet_not_found": "Account information is temporarily unavailable. Please try again later.",
        "creator_role_template_wrong_app": "Role templates are not available for this product.",
        "creator_role_templates_disabled": "Role templates are temporarily unavailable. Please try again later.",
        "creator_role_template_not_found": "The role template does not exist or has been deleted.",
        "creator_role_template_not_eligible": "This account is not currently eligible to create role templates.",
        "creator_role_template_limit_reached": "You can have up to 3 active templates.",
        "creator_role_template_state_conflict": "The template changed. Refresh the page and try again.",
        "creator_role_template_disabled_by_admin": "The template was disabled by the platform and cannot be changed.",
        "creator_role_template_expired": "The template has expired and cannot be changed.",
        "creator_role_template_no_changes": "The template has no changes to submit.",
        "creator_role_template_version_not_found": "The template version could not be found. Refresh and try again.",
        "creator_role_template_version_not_approved": "Only approved versions can be published.",
        "role_review_in_progress": "The template is under review. Check again later.",
        "role_review_pending": "The template is waiting for review. Please try again later.",
        "role_review_not_pending": "This version is not waiting for review. Refresh and try again.",
        "role_review_unavailable": "Review is temporarily unavailable. Please try again later.",
        "ai_name_length_invalid": "The role name has an invalid length. Revise it and try again.",
        "ai_name_must_be_single_line": "The role name must be a single line.",
        "ai_name_contains_control_characters": "The role name contains unsupported characters.",
        "personality_text_length_invalid": "The personality text has an invalid length. Revise it and try again.",
        "personality_text_contains_control_characters": "The personality text contains unsupported characters.",
        "mission_text_length_invalid": "The mission text has an invalid length. Revise it and try again.",
        "mission_text_contains_control_characters": "The mission text contains unsupported characters.",
        "opening_line_length_invalid": "The opening line has an invalid length. Revise it and try again.",
        "opening_line_contains_control_characters": "The opening line contains unsupported characters.",
        "public_summary_length_invalid": "The summary has an invalid length. Revise it and try again.",
        "public_summary_must_be_single_line": "The summary must be a single line.",
        "public_summary_contains_control_characters": "The summary contains unsupported characters.",
        "public_summary_must_include_ai_name": "The summary must include the role name.",
        "creator_role_template_summary_edit_unavailable": "This version's summary can no longer be edited.",
        "creator_role_template_summary_review_in_progress": "The summary is under review. Refresh later.",
        "creator_role_template_summary_review_unavailable": "Summary review is temporarily unavailable. This attempt was not used; try again later.",
        "creator_role_template_summary_rejected": "Your edited summary did not pass review, so the original summary was kept.",
        "stats_range_invalid": "The statistics date range is invalid. Adjust it and try again.",
        "faq_message_not_found": "The message does not exist or has been removed.",
        "role_template_unavailable": "The role template is temporarily unavailable. It will be checked again during registration.",
        "otp_code_required": "Enter the verification code.",
        "invite_code_invalid": "This invitation code is unavailable.",
        "invite_code_check_failed": "The invitation code could not be verified. Please try again later.",
        "phone_verification_required": "Verify your phone number first.",
        "binding_expired": "The QR code has expired. Please verify again.",
        "copy_failed": "Copy failed. Select and copy the text manually.",
        "invite_information_loading": "Invitation information is still loading. Please try again shortly.",
        "invite_code_unavailable": "The invitation code is temporarily unavailable. Refresh and try again.",
        "role_fields_required": "Name, personality, mission, and opening line are all required.",
        "rate_limit_daily": "We've chatted a lot today. I'll be here to continue later.",
        "rate_limit_rpm": "Messages are arriving too quickly. Wait a moment and try again.",
        "generation_error": "I got a little stuck just now. Please send that again in a moment.",
        "moderation_outbound_blocked": "I can't send that response. Let's switch to a safer topic.",
        "moderation_inbound_blocked": "I can't continue with that topic. Let's talk about something lighter.",
        "image_understanding_failed": "I couldn't make out that image. Tell me about it or send it again.",
        "voice_understanding_failed": "I couldn't hear that voice message clearly. Type it or send it again.",
        "session_reset": "The current conversation has been reset.",
        "onboarding_welcome": "Hi, I'm glad we're connected on WeChat. What would you like me to call you?",
        "app_auth_welcome": "Hi, I'm {name}. Would you like to talk about how you feel right now, or just chat about anything?",
        "tool_policy_required": "The tool configuration is incomplete and cannot run right now.",
        "tool_policy_scope_mismatch": "This tool does not match the current product.",
        "tool_unknown": "This tool is not supported.",
        "tool_not_allowed": "This product does not allow that tool.",
        "tool_disabled": "This tool is currently disabled.",
        "tool_execution_failed": "The tool failed. Please try again later.",
        "commitment_text_required": "Follow-up content is required.",
        "commitment_account_unavailable": "The account is unavailable, so the follow-up cannot be saved.",
        "commitment_due_at_invalid": "The follow-up time must be in the future.",
        "commitment_due_at_too_far": "The follow-up time is outside the allowed range.",
        "reminder_fulfillment_invalid": "The reminder type is invalid. Set it again.",
        "reminder_text_required": "Reminder content is required.",
        "reminder_time_invalid": "The reminder time is invalid. Set it again.",
        "reminder_recurrence_invalid": "The reminder recurrence is invalid. Set it again.",
        "reminder_route_missing": "No delivery target is available for this reminder.",
        "dynamic_reminder_unavailable": "Scheduled briefings are not available right now.",
        "dynamic_reminder_limit_reached": "The scheduled briefing limit has been reached. Cancel one before creating another.",
        "reminder_id_required": "A reminder ID is required.",
        "reminder_not_found": "The reminder does not exist or cannot be accessed.",
        "reminder_state_invalid": "The reminder's current state does not allow this action.",
        "reminder_update_empty": "No reminder changes were provided.",
        "reminder_update_failed": "The reminder could not be updated. Please try again later.",
        "content_topic_required": "A content topic is required.",
        "invitation_text_required": "Invitation content is required.",
        "invitation_url_forbidden": "Proactive invitation content cannot contain links.",
        "invitation_titles_insufficient": "At least 3 titles are required.",
        "invitation_not_found": "The content invitation does not exist or cannot be accessed.",
        "invitation_state_invalid": "The invitation's current state does not allow this action.",
        "invitation_expired": "The content invitation has expired.",
        "invitation_update_failed": "The content invitation could not be updated. Please try again later.",
        "feedback_type_invalid": "The feedback type is invalid.",
        "proactive_fields_unsupported": "The request contains unsupported proactive-message settings.",
        "proactive_update_empty": "No proactive-message setting changes were provided.",
        "proactive_settings_invalid": "The proactive-message settings are invalid. Check them and try again.",
        "mission_not_assigned": "No mission has been assigned yet.",
        "mission_content_required": "Mission content is required.",
    },
    "ja-JP": {
        "generic_error": "操作に失敗しました。しばらくしてからもう一度お試しください。",
        "invalid_request": "リクエスト内容が正しくありません。確認してもう一度お試しください。",
        "not_authenticated": "続行するにはログインしてください。",
        "session_expired": "ログインの有効期限が切れました。もう一度認証してください。",
        "not_found": "対象が見つからないか、すでに利用できません。",
        "rate_limited": "操作が多すぎます。しばらくしてからもう一度お試しください。",
        "service_unavailable": "サービスは一時的に利用できません。しばらくしてからお試しください。",
        "account_disabled": "このアカウントは停止されているため、現在利用できません。",
        "account_not_ready": "アカウントの準備が完了していません。しばらくしてからお試しください。",
        "invalid_phone": "有効な中国本土の携帯電話番号を入力してください。",
        "captcha_failed": "認証に失敗しました。もう一度お試しください。",
        "sms_rate_limited": "SMS の送信回数が多すぎます。しばらくしてからお試しください。",
        "sms_send_failed": "認証メッセージを送信できませんでした。しばらくしてからお試しください。",
        "otp_not_found_or_expired": "認証コードが存在しないか期限切れです。新しいコードを取得してください。",
        "otp_attempts_exceeded": "試行回数が多すぎます。新しい認証コードを取得してください。",
        "otp_invalid": "認証コードが正しくありません。確認してもう一度お試しください。",
        "verification_token_invalid": "認証情報が無効か期限切れです。もう一度認証してください。",
        "profile_update_empty": "プロフィールを少なくとも1項目変更してください。",
        "display_name_invalid": "表示名が正しくありません。修正してもう一度お試しください。",
        "avatar_key_invalid": "選択したアバターは無効です。別のものを選んでください。",
        "content_rejected": "送信内容は安全確認を通過しませんでした。修正してもう一度お試しください。",
        "content_review_unavailable": "コンテンツ審査は一時的に利用できません。しばらくしてからお試しください。",
        "deletion_not_confirmed": "確認してからアカウント削除を実行してください。",
        "reason_code_invalid": "削除理由が無効です。別の項目を選択してください。",
        "turn_in_progress": "前のメッセージを処理中です。少し待ってからお試しください。",
        "audio_too_long": "音声が長すぎます。短くしてもう一度お試しください。",
        "unsupported_audio_type": "この音声形式には対応していません。別の形式をお試しください。",
        "empty_audio": "音声を読み取れませんでした。もう一度録音してください。",
        "audio_too_large": "音声ファイルが大きすぎます。短くしてもう一度お試しください。",
        "asr_not_configured": "音声認識は現在利用できません。後で試すか文字で入力してください。",
        "asr_provider_failed": "音声認識に失敗しました。後で試すか文字で入力してください。",
        "binding_failed": "WeChat の連携に失敗しました。ページを更新してもう一度お試しください。",
        "binding_gateway_unavailable": "WeChat 連携は一時的に利用できません。しばらくしてからお試しください。",
        "binding_qr_unavailable": "連携用QRコードを作成できませんでした。しばらくしてからお試しください。",
        "binding_already_connected": "このWeChatアカウントはすでに連携されています。元の連携を解除してからお試しください。",
        "binding_intent_not_found": "連携リクエストが存在しないか期限切れです。もう一度開始してください。",
        "wallet_not_found": "アカウント情報を取得できません。しばらくしてからお試しください。",
        "creator_role_template_wrong_app": "このプロダクトではロールテンプレートを利用できません。",
        "creator_role_templates_disabled": "ロールテンプレートは一時的に利用できません。",
        "creator_role_template_not_found": "ロールテンプレートが存在しないか、削除されています。",
        "creator_role_template_not_eligible": "このアカウントは現在ロールテンプレートを作成できません。",
        "creator_role_template_limit_reached": "有効なテンプレートは最大3件まで保持できます。",
        "creator_role_template_state_conflict": "テンプレートの状態が変わりました。更新してもう一度お試しください。",
        "creator_role_template_disabled_by_admin": "このテンプレートはプラットフォームにより停止されています。",
        "creator_role_template_expired": "このテンプレートは期限切れのため操作できません。",
        "creator_role_template_no_changes": "テンプレート内容に変更はありません。",
        "creator_role_template_version_not_found": "テンプレートのバージョンが見つかりません。更新してお試しください。",
        "creator_role_template_version_not_approved": "審査承認済みのバージョンのみ公開できます。",
        "role_review_in_progress": "テンプレートを審査中です。しばらくしてからご確認ください。",
        "role_review_pending": "テンプレートは審査待ちです。しばらくしてからお試しください。",
        "role_review_not_pending": "このバージョンは審査待ちではありません。更新してお試しください。",
        "role_review_unavailable": "審査は一時的に利用できません。しばらくしてからお試しください。",
        "ai_name_length_invalid": "ロール名の長さが正しくありません。修正してください。",
        "ai_name_must_be_single_line": "ロール名は1行で入力してください。",
        "ai_name_contains_control_characters": "ロール名に使用できない文字が含まれています。",
        "personality_text_length_invalid": "性格設定の長さが正しくありません。修正してください。",
        "personality_text_contains_control_characters": "性格設定に使用できない文字が含まれています。",
        "mission_text_length_invalid": "使命の長さが正しくありません。修正してください。",
        "mission_text_contains_control_characters": "使命に使用できない文字が含まれています。",
        "opening_line_length_invalid": "最初のメッセージの長さが正しくありません。修正して再試行してください。",
        "opening_line_contains_control_characters": "最初のメッセージに使用できない文字が含まれています。",
        "public_summary_length_invalid": "紹介文の長さが正しくありません。修正して再試行してください。",
        "public_summary_must_be_single_line": "紹介文は1行で入力してください。",
        "public_summary_contains_control_characters": "紹介文に使用できない文字が含まれています。",
        "public_summary_must_include_ai_name": "紹介文にはキャラクター名を含めてください。",
        "creator_role_template_summary_edit_unavailable": "このバージョンの紹介文はこれ以上編集できません。",
        "creator_role_template_summary_review_in_progress": "紹介文を審査中です。しばらくしてから更新してください。",
        "creator_role_template_summary_review_unavailable": "紹介文の審査サービスは一時的に利用できません。変更機会は消費されていません。",
        "creator_role_template_summary_rejected": "編集した紹介文は審査を通過しなかったため、元の紹介文を保持しました。",
        "stats_range_invalid": "統計の日付範囲が正しくありません。修正してお試しください。",
        "faq_message_not_found": "メッセージが存在しないか、削除されています。",
        "role_template_unavailable": "ロールテンプレートは一時的に利用できません。登録時に再確認されます。",
        "otp_code_required": "認証コードを入力してください。",
        "invite_code_invalid": "この招待コードは利用できません。",
        "invite_code_check_failed": "招待コードを確認できませんでした。しばらくしてからお試しください。",
        "phone_verification_required": "先に携帯電話番号の認証を完了してください。",
        "binding_expired": "QRコードの有効期限が切れました。もう一度認証してください。",
        "copy_failed": "コピーできませんでした。テキストを選択して手動でコピーしてください。",
        "invite_information_loading": "招待情報を読み込み中です。しばらくしてからお試しください。",
        "invite_code_unavailable": "招待コードを取得できません。更新してもう一度お試しください。",
        "role_fields_required": "名前、性格・背景、使命、最初のメッセージをすべて入力してください。",
        "rate_limit_daily": "今日はたくさん話しましたね。また少し後で続きを話しましょう。",
        "rate_limit_rpm": "メッセージが続いています。少し待ってから送ってください。",
        "generation_error": "少し処理に詰まってしまいました。少し後でもう一度送ってください。",
        "moderation_outbound_blocked": "その内容は送信できません。別の安全な話題にしましょう。",
        "moderation_inbound_blocked": "その話題は続けられません。もう少し気軽な話題にしましょう。",
        "image_understanding_failed": "画像をうまく確認できませんでした。説明するか、もう一度送ってください。",
        "voice_understanding_failed": "音声をはっきり聞き取れませんでした。文字で伝えるか、もう一度送ってください。",
        "session_reset": "現在の会話をリセットしました。",
        "onboarding_welcome": "こんにちは。WeChatでつながれてうれしいです。どのようにお呼びすればよいですか？",
        "app_auth_welcome": "こんにちは、{name}です。今の気持ちを話してみますか？それとも気軽におしゃべりしますか？",
        "tool_policy_required": "ツール設定が不足しているため、現在実行できません。",
        "tool_policy_scope_mismatch": "このツールは現在のプロダクトと一致しません。",
        "tool_unknown": "このツールには対応していません。",
        "tool_not_allowed": "このプロダクトではこのツールを利用できません。",
        "tool_disabled": "このツールは現在無効です。",
        "tool_execution_failed": "ツールの実行に失敗しました。しばらくしてからお試しください。",
        "commitment_text_required": "フォローアップ内容を入力してください。",
        "commitment_account_unavailable": "アカウントを利用できないため、フォローアップを記録できません。",
        "commitment_due_at_invalid": "フォローアップ時刻は未来の時刻を指定してください。",
        "commitment_due_at_too_far": "フォローアップ時刻が設定可能な範囲を超えています。",
        "reminder_fulfillment_invalid": "リマインダーの種類が無効です。設定し直してください。",
        "reminder_text_required": "リマインダー内容を入力してください。",
        "reminder_time_invalid": "リマインダー時刻が無効です。設定し直してください。",
        "reminder_recurrence_invalid": "繰り返しルールが無効です。設定し直してください。",
        "reminder_route_missing": "送信先がないため、リマインダーを作成できません。",
        "dynamic_reminder_unavailable": "定期ブリーフィングは現在利用できません。",
        "dynamic_reminder_limit_reached": "定期ブリーフィングが上限に達しました。1件解除してから作成してください。",
        "reminder_id_required": "リマインダーIDが必要です。",
        "reminder_not_found": "リマインダーが存在しないか、操作する権限がありません。",
        "reminder_state_invalid": "現在のリマインダー状態ではこの操作を実行できません。",
        "reminder_update_empty": "変更するリマインダー内容がありません。",
        "reminder_update_failed": "リマインダーを更新できませんでした。しばらくしてからお試しください。",
        "content_topic_required": "コンテンツのテーマを入力してください。",
        "invitation_text_required": "招待内容を入力してください。",
        "invitation_url_forbidden": "能動的な招待内容にリンクは含められません。",
        "invitation_titles_insufficient": "タイトルは3件以上必要です。",
        "invitation_not_found": "コンテンツ招待が存在しないか、操作する権限がありません。",
        "invitation_state_invalid": "現在の招待状態ではこの操作を実行できません。",
        "invitation_expired": "コンテンツ招待は期限切れです。",
        "invitation_update_failed": "コンテンツ招待を更新できませんでした。しばらくしてからお試しください。",
        "feedback_type_invalid": "フィードバックの種類が無効です。",
        "proactive_fields_unsupported": "対応していない能動メッセージ設定が含まれています。",
        "proactive_update_empty": "変更する能動メッセージ設定がありません。",
        "proactive_settings_invalid": "能動メッセージ設定が無効です。確認してもう一度お試しください。",
        "mission_not_assigned": "使命はまだ割り当てられていません。",
        "mission_content_required": "使命の内容を入力してください。",
    },
}

_LEGACY_DETAIL_CODES = {
    "未登录": "not_authenticated",
    "登录已过期，请重新验证": "session_expired",
    "验证码校验未通过": "captcha_failed",
    "发送频率过高，请稍后重试": "sms_rate_limited",
    "短信发送失败，请稍后重试": "sms_send_failed",
    "验证码不存在或已过期，请重新获取": "otp_not_found_or_expired",
    "尝试次数过多，请重新获取验证码": "otp_attempts_exceeded",
    "验证码错误": "otp_invalid",
    "注册凭证无效或已过期": "verification_token_invalid",
    "验证凭证无效或已过期": "verification_token_invalid",
    "phone must be a valid Chinese mobile number (1[3-9]XXXXXXXXX)": "invalid_phone",
    "binding_intent not found": "binding_intent_not_found",
    "wallet not found": "wallet_not_found",
    "faq message not found": "faq_message_not_found",
}

_STATUS_FALLBACK_CODES = {
    400: "invalid_request",
    401: "not_authenticated",
    403: "invalid_request",
    404: "not_found",
    409: "invalid_request",
    413: "invalid_request",
    415: "invalid_request",
    422: "invalid_request",
    429: "rate_limited",
    500: "generic_error",
    502: "service_unavailable",
    503: "service_unavailable",
}

_WEB_MESSAGE_KEYS = (
    "generic_error",
    "invalid_request",
    "not_authenticated",
    "session_expired",
    "rate_limited",
    "service_unavailable",
    "binding_failed",
    "binding_gateway_unavailable",
    "binding_qr_unavailable",
    "binding_already_connected",
    "binding_intent_not_found",
    "creator_role_template_limit_reached",
    "creator_role_templates_disabled",
    "stats_range_invalid",
    "role_template_unavailable",
    "otp_code_required",
    "invite_code_invalid",
    "invite_code_check_failed",
    "phone_verification_required",
    "binding_expired",
    "copy_failed",
    "invite_information_loading",
    "invite_code_unavailable",
    "role_fields_required",
)


def product_default_language(app_id: str = MINGCHAN_APP_ID) -> str:
    """返回服务端可信产品注册项的默认语言。"""

    return PRODUCTION_PRODUCT_REGISTRY.require_registered(app_id).default_language


def product_message(
    key: str,
    *,
    app_id: str = MINGCHAN_APP_ID,
    language: Optional[str] = None,
    **params: Any,
) -> str:
    """按产品语言解析固定文案；缺失键安全回落为通用错误。"""

    resolved = language or product_default_language(app_id)
    catalog = _MESSAGES.get(resolved) or _MESSAGES["zh-CN"]
    template = catalog.get(str(key or "")) or catalog["generic_error"]
    try:
        return template.format(**params)
    except (KeyError, ValueError):
        return catalog["generic_error"]


def normalize_public_error_code(detail: object, *, status_code: int) -> str:
    """把遗留长文本收敛为稳定英文码，未知详情不向用户透传。"""

    text = str(detail or "").strip()
    legacy = _LEGACY_DETAIL_CODES.get(text)
    if legacy:
        return legacy
    if _MACHINE_CODE_RE.fullmatch(text):
        return text
    return _STATUS_FALLBACK_CODES.get(int(status_code), "generic_error")


def public_error_message(
    code: str,
    *,
    status_code: int,
    app_id: str = MINGCHAN_APP_ID,
) -> str:
    """为公开错误码生成用户可见消息，未知码按 HTTP 状态安全回落。"""

    language = product_default_language(app_id)
    catalog = _MESSAGES.get(language) or _MESSAGES["zh-CN"]
    if code in catalog:
        return product_message(code, app_id=app_id, language=language)
    fallback = _STATUS_FALLBACK_CODES.get(int(status_code), "generic_error")
    return product_message(fallback, app_id=app_id, language=language)


def public_web_messages(
    *, app_id: str = MINGCHAN_APP_ID, language: Optional[str] = None
) -> Dict[str, str]:
    """返回静态用户页需要的精简错误文案目录。"""

    resolved = language or product_default_language(app_id)
    return {
        key: product_message(key, app_id=app_id, language=resolved)
        for key in _WEB_MESSAGE_KEYS
    }


def localized_tool_error(
    code: str,
    *,
    app_id: str = MINGCHAN_APP_ID,
    message_key: Optional[str] = None,
    **params: Any,
) -> Dict[str, str]:
    """构造供模型消费的稳定工具错误码与产品语言消息。"""

    return {
        "error_code": str(code),
        "error": product_message(message_key or code, app_id=app_id, **params),
    }


__all__ = [
    "localized_tool_error",
    "normalize_public_error_code",
    "product_default_language",
    "product_message",
    "public_error_message",
    "public_web_messages",
]
