"""Companion World product domain layer（朝夕相伴 多居民私人世界）。

分层不变量：本包只经 agent_runtime 端口访问 Agent Runtime，禁止直接
import app.db.* / app.turn_service（由 tests/test_layer_boundaries.py 的
stdlib-AST 边界门禁执行，D-12）。
"""
from app.products.zhaoxi.domain.companion_world.contracts import (  # noqa: F401
    BootstrapResult,
    AppNotificationRecord,
    AppNotificationRepository,
    CandidateRecord,
    CompanionWorldError,
    ConversationMessage,
    ConversationReadState,
    ConversationSummary,
    ConversationTarget,
    FeedRepository,
    ResidentRecord,
    ResidentDraftRecord,
    ResidentSelection,
    TemplateDraft,
    TemplateRecord,
    UniversePostRecord,
    WorldRecord,
    WorldOutboxRecord,
    WorldRepository,
)
from app.products.zhaoxi.domain.companion_world.service import CompanionWorldService  # noqa: F401
from app.products.zhaoxi.domain.companion_world.feed import (  # noqa: F401
    MAX_FEED_POST_IMAGES,
    CompanionWorldFeedService,
    user_post_fingerprint,
)
from app.products.zhaoxi.domain.companion_world.notifications import (  # noqa: F401
    CompanionWorldNotificationService,
)
from app.products.zhaoxi.domain.companion_world.proactive import (  # noqa: F401
    HUMAN_PROACTIVE_CATEGORIES,
    HumanProactiveDecision,
    HumanProactiveScope,
    HumanProactiveSpeaker,
    allows_speaker_reselection,
    decide_human_proactive_delivery,
    is_human_proactive_category,
)
from app.products.zhaoxi.domain.companion_world.memory_sink import (  # noqa: F401
    CompanionWorldMemorySink,
)
from app.products.zhaoxi.domain.companion_world.lifecycle import (  # noqa: F401
    LIFECYCLE_CRISIS_CATEGORIES,
    LIFECYCLE_EVENT_STATUSES,
    LIFECYCLE_EVENT_TYPES,
    LIFECYCLE_SEVERE_ABUSE_CATEGORIES,
    LifecycleActionRecord,
    LifecycleEvidenceRef,
    LifecycleEventRecord,
    LifecyclePolicy,
    LifecycleRepository,
    inactivity_is_due,
    inactivity_threshold_at,
    latest_crisis_freeze_until,
    lifecycle_event_fingerprint,
    lifecycle_transition_allowed,
    normalize_lifecycle_category,
    redact_lifecycle_evidence_refs,
    severe_abuse_evidence,
    value_misalignment_evidence,
)
from app.products.zhaoxi.domain.companion_world.mailbox import (  # noqa: F401
    LETTER_OPEN_STATUSES,
    LETTER_TERMINAL_STATUSES,
    CharacterLetterRecord,
    LetterCatalogRecord,
    MailboxPolicy,
    MailboxRepository,
    letter_delivery_fingerprint,
    letter_is_open,
    letter_transition_allowed,
)

__all__ = [
    "BootstrapResult",
    "AppNotificationRecord",
    "AppNotificationRepository",
    "CandidateRecord",
    "CompanionWorldError",
    "CompanionWorldMemorySink",
    "CompanionWorldNotificationService",
    "CompanionWorldFeedService",
    "CompanionWorldService",
    "ConversationMessage",
    "ConversationReadState",
    "ConversationSummary",
    "ConversationTarget",
    "FeedRepository",
    "HUMAN_PROACTIVE_CATEGORIES",
    "LIFECYCLE_CRISIS_CATEGORIES",
    "LIFECYCLE_EVENT_STATUSES",
    "LIFECYCLE_EVENT_TYPES",
    "LIFECYCLE_SEVERE_ABUSE_CATEGORIES",
    "LETTER_OPEN_STATUSES",
    "LETTER_TERMINAL_STATUSES",
    "LifecycleActionRecord",
    "LifecycleEvidenceRef",
    "LifecycleEventRecord",
    "LifecyclePolicy",
    "LifecycleRepository",
    "CharacterLetterRecord",
    "LetterCatalogRecord",
    "MailboxRepository",
    "MailboxPolicy",
    "HumanProactiveDecision",
    "HumanProactiveScope",
    "HumanProactiveSpeaker",
    "ResidentRecord",
    "ResidentDraftRecord",
    "ResidentSelection",
    "TemplateDraft",
    "TemplateRecord",
    "UniversePostRecord",
    "WorldRecord",
    "WorldOutboxRecord",
    "WorldRepository",
    "allows_speaker_reselection",
    "decide_human_proactive_delivery",
    "is_human_proactive_category",
    "inactivity_is_due",
    "inactivity_threshold_at",
    "latest_crisis_freeze_until",
    "lifecycle_event_fingerprint",
    "lifecycle_transition_allowed",
    "normalize_lifecycle_category",
    "redact_lifecycle_evidence_refs",
    "severe_abuse_evidence",
    "value_misalignment_evidence",
    "letter_delivery_fingerprint",
    "letter_is_open",
    "letter_transition_allowed",
    "user_post_fingerprint",
]
