"""朝夕公开 Web 页面与 FAQ 的产品级展示文案。"""
from __future__ import annotations

from typing import Dict, List, Optional

from app.bootstrap.product_registry import ZHAOXI_APP_ID
from app.products.zhaoxi.application.product_localization import (
    product_default_language,
)


_WEB_UI_MESSAGES: Dict[str, Dict[str, str]] = {
    "zh-CN": {
        "page_brand": "朝夕相伴",
        "beta_label": "Beta 测试版",
        "nav_home": "首页",
        "nav_faq": "常见问题",
        "nav_dashboard": "用户中心",
        "nav_back_dashboard": "返回用户中心",
        "logout": "退出登录",
        "loading": "加载中…",
        "cancel": "取消",
        "home_page_title": "朝夕相伴 — 你的微信专属 AI 陪伴",
        "home_beta_stage": "当前处于小范围测试阶段",
        "home_tagline": "你的微信专属 AI 陪伴\n陪聊、提醒、记录生活点滴",
        "home_subtitle": "手机号验证 · 微信扫码接入 · 开箱即用\n每个用户独立 AI，完全属于你自己",
        "home_login_title": "手机号注册 / 登录",
        "home_mobile_qr_note": "如果你正在手机浏览器中打开，请长按二维码完成绑定，或截图保存后，再到微信中识别二维码完成绑定。",
        "phone_label": "手机号",
        "phone_placeholder": "请输入手机号",
        "otp_label": "验证码",
        "otp_placeholder": "6 位验证码",
        "get_otp": "获取验证码",
        "get_otp_countdown": "获取验证码 ({seconds}s)",
        "resend_otp": "重发",
        "verify_continue": "验证并继续",
        "qr_alt": "微信扫码二维码",
        "qr_scan_caption": "请用要接入的微信号扫描二维码",
        "qr_waiting": "等待扫码中…",
        "login_redirecting": "登录成功，正在跳转…",
        "enter_dashboard": "进入用户中心",
        "invite_code_applied": "已带入邀请码 {code}",
        "role_will_create": "将创建角色：{name}",
        "role_default_name": "朝夕伙伴",
        "role_personality_preview": "性格 / 底色：{value}",
        "role_mission_preview": "使命：{value}",
        "role_summary_preview": "简介：{value}",
        "role_expiry_preview": "模板有效期至：{value}",
        "bind_wechat_title": "扫码绑定微信",
        "session_binding_qr_loading": "检测到你已登录，正在生成微信绑定二维码…",
        "sending": "发送中…",
        "otp_sent_to": "验证码已发送到 {phone}",
        "verifying": "验证中…",
        "logging_in": "登录中…",
        "qr_generating": "正在生成二维码…",
        "binding_success": "绑定成功 ✓",
        "dashboard_page_title": "用户中心 — 朝夕相伴",
        "dashboard_my_account": "我的账号",
        "dashboard_account_id": "Account ID",
        "dashboard_plan": "套餐",
        "dashboard_registered_at": "注册时间",
        "dashboard_wallet": "贝壳余额",
        "dashboard_shells": "贝壳",
        "dashboard_wallet_note": "内测期间赠送贝壳，充值套餐即将上线",
        "dashboard_top_up_soon": "充值（敬请期待）",
        "dashboard_invite_friends": "邀请好友",
        "dashboard_invite_intro": "把专属注册链接发给朋友。朋友通过链接注册并绑定微信后，邀请关系会自动记录。",
        "dashboard_my_invite_code": "我的邀请码",
        "dashboard_registration_link": "注册链接",
        "dashboard_copy_invite_code": "复制邀请码",
        "dashboard_copy_link": "复制链接",
        "dashboard_share_loading": "正在生成分享文案…",
        "dashboard_copy_share": "复制分享文案",
        "dashboard_role_templates": "自定义角色模板管理",
        "dashboard_role_templates_intro": "可以自定义创建AI角色模板，可分享给好友或他人使用",
        "enter": "进入",
        "dashboard_wechat_binding": "微信绑定",
        "dashboard_unbind": "解绑",
        "dashboard_binding_status": "绑定状态",
        "dashboard_checking": "检查中…",
        "dashboard_last_active": "最近活跃",
        "dashboard_unbind_confirm_title": "确认解绑",
        "dashboard_unbind_warning": "解绑后，AI 将停止回复微信消息。\n记忆、对话记录和 AI 设置将被永久删除，无法恢复。",
        "dashboard_unbind_confirm": "确认解绑",
        "dashboard_more_soon": "更多功能（历史记录、通知设置）即将上线",
        "dashboard_share_text": "我在用朝夕相伴，注册时用我的邀请码 {code}，一起体验微信专属 AI 陪伴：{link}",
        "dashboard_invite_count": "已邀请 {count} 人",
        "dashboard_invite_code_copied": "邀请码已复制",
        "dashboard_link_copied": "注册链接已复制",
        "dashboard_share_copied": "分享文案已复制",
        "dashboard_bound": "✓ 已绑定",
        "dashboard_unbound": "未绑定",
        "processing": "处理中…",
        "creator_page_title": "角色模板邀请链接 — 朝夕相伴",
        "creator_heading": "角色模板邀请链接",
        "creator_intro": "创建角色的姓名、性格/底色、使命和开场白。审核通过后会生成一句话简介，发布后可分享注册链接。",
        "creator_new": "新建角色模板",
        "creator_edit": "编辑角色模板",
        "creator_name": "姓名",
        "creator_name_placeholder": "例如：小满",
        "creator_personality": "性格 / 底色",
        "creator_personality_placeholder": "描述这个 AI 如何理解世界、如何与你相处、表达风格和边界。",
        "creator_mission": "使命",
        "creator_mission_placeholder": "描述它希望长期为用户带来什么，不需要填写量化指标。",
        "creator_opening_line": "开场白",
        "creator_opening_line_placeholder": "用户告诉角色称呼后，角色第一次对用户说的话。",
        "creator_public_summary": "一句话简介",
        "creator_summary_edit_label": "修改一句话简介（仅有一次正式提交机会）",
        "creator_summary_edit_note": "简介必须包含角色姓名。审核通过或拒绝后，本版本都不能再次修改；服务异常不会消耗机会。",
        "creator_summary_submit": "提交简介修改",
        "creator_summary_reviewing": "一句话简介正在审核中，请稍后刷新。",
        "creator_summary_required": "请输入一句话简介。",
        "creator_summary_submitting": "审核中…",
        "creator_summary_success": "修改成功",
        "creator_submit": "提交并审核",
        "creator_unnamed": "未命名模板",
        "creator_unknown_status": "状态未知",
        "creator_used_count": "已实例化 {count} 次",
        "creator_latest_review": "最新审核",
        "creator_review_reason": "审核理由",
        "creator_activated_at": "首次激活",
        "creator_expires_at": "有效期至",
        "creator_version_note": "当前注册链接仍使用已发布的 v{published}；上面的 v{latest} 需要审核通过并主动发布后才会生效。",
        "creator_edit_content": "编辑模板内容",
        "creator_retry_review": "重试审核",
        "creator_publish_version": "发布此版本",
        "creator_disable_link": "停用链接",
        "creator_enable_link": "恢复链接",
        "creator_copy_link": "复制注册链接",
        "creator_view_stats": "查看统计",
        "creator_delete": "删除",
        "creator_empty": "你还没有角色模板。最多可以拥有 3 个有效模板。",
        "creator_submitting": "提交审核中…",
        "creator_submitted": "已提交并完成本次审核尝试。",
        "creator_action_success": "操作成功。",
        "creator_publish_success": "发布成功，360 天有效期从首次激活时间起算。",
        "creator_delete_confirm": "确认删除角色模板“{name}”？删除后链接立即失效，且不能恢复。",
        "creator_deleted": "模板已删除。",
        "creator_link_copied": "注册链接已复制。",
        "creator_stats_loading": "统计加载中…",
        "creator_stats_heading": "最近 14 个北京自然日漏斗",
        "creator_stats_pv": "曝光 PV",
        "creator_stats_uv": "曝光 UV",
        "creator_stats_registered": "注册",
        "creator_stats_scanned": "扫码",
        "creator_stats_activated": "激活",
        "creator_stats_completed": "Onboarding 完成",
        "onboarding_page_title": "微信接入 — 朝夕相伴",
        "onboarding_back_admin": "返回运营后台",
        "onboarding_register": "手机号注册",
        "onboarding_invite_code": "邀请码",
        "onboarding_optional": "可选",
        "onboarding_verify_register": "验证并注册",
        "onboarding_resend": "重新发送",
        "onboarding_scan_login": "扫码登录微信",
        "onboarding_refresh": "刷新状态",
        "onboarding_connected": "✅ 微信扫码连接成功！请现在用微信给 AI 发一条消息，激活对话。",
        "onboarding_scan_caption": "请用要接入 AI4ALL 的微信扫码。",
        "onboarding_qr_hint": "手机端打开？长按上方二维码 → 选择「识别图中二维码」完成连接。",
        "onboarding_status": "状态",
        "onboarding_expires": "过期时间",
        "onboarding_manual_command": "调试兜底命令",
        "onboarding_qr_missing": "后端暂未返回二维码，请查看状态或使用调试兜底命令排查。",
        "onboarding_current_object": "当前对象",
        "onboarding_otp_sent": "验证码已发送",
        "onboarding_invite_valid": "邀请码可用",
        "onboarding_verified_qr": "验证通过，正在生成二维码…",
        "onboarding_registering": "注册中…",
        "onboarding_registered": "注册成功",
        "onboarding_binding_created": "正在发起 OpenClaw QR 登录",
        "onboarding_binding_qr": "二维码已生成，等待扫码",
        "onboarding_binding_completed": "绑定完成，后续消息会进入该账号",
        "refreshing": "刷新中…",
        "faq_page_title": "常见问题 - 朝夕相伴",
        "faq_heading": "常见问题",
    },
    "en-US": {
        "page_brand": "朝夕相伴",
        "beta_label": "Beta",
        "nav_home": "Home",
        "nav_faq": "FAQ",
        "nav_dashboard": "Account",
        "nav_back_dashboard": "Back to account",
        "logout": "Sign out",
        "loading": "Loading…",
        "cancel": "Cancel",
        "home_page_title": "朝夕相伴 — Your personal AI companion on WeChat",
        "home_beta_stage": "Currently in limited beta",
        "home_tagline": "Your personal AI companion on WeChat\nChat, reminders, and everyday memories",
        "home_subtitle": "Verify your phone · Connect WeChat · Start right away\nA private, independent AI for every user",
        "home_login_title": "Register / Sign in with phone",
        "home_mobile_qr_note": "On mobile, press and hold the QR code to connect, or save a screenshot and scan it from WeChat.",
        "phone_label": "Phone number",
        "phone_placeholder": "Enter your phone number",
        "otp_label": "Verification code",
        "otp_placeholder": "6-digit code",
        "get_otp": "Get code",
        "get_otp_countdown": "Get code ({seconds}s)",
        "resend_otp": "Resend",
        "verify_continue": "Verify and continue",
        "qr_alt": "WeChat connection QR code",
        "qr_scan_caption": "Scan with the WeChat account you want to connect",
        "qr_waiting": "Waiting for scan…",
        "login_redirecting": "Signed in. Redirecting…",
        "enter_dashboard": "Open account center",
        "invite_code_applied": "Invite code applied: {code}",
        "role_will_create": "Role to be created: {name}",
        "role_default_name": "Your AI companion",
        "role_personality_preview": "Personality: {value}",
        "role_mission_preview": "Mission: {value}",
        "role_summary_preview": "Summary: {value}",
        "role_expiry_preview": "Template valid until: {value}",
        "bind_wechat_title": "Connect WeChat",
        "session_binding_qr_loading": "You're signed in. Creating a WeChat connection QR code…",
        "sending": "Sending…",
        "otp_sent_to": "Verification code sent to {phone}",
        "verifying": "Verifying…",
        "logging_in": "Signing in…",
        "qr_generating": "Creating QR code…",
        "binding_success": "Connected ✓",
        "dashboard_page_title": "Account Center — 朝夕相伴",
        "dashboard_my_account": "My account",
        "dashboard_account_id": "Account ID",
        "dashboard_plan": "Plan",
        "dashboard_registered_at": "Registered",
        "dashboard_wallet": "Shell balance",
        "dashboard_shells": "shells",
        "dashboard_wallet_note": "Complimentary shells are provided during beta. Paid plans are coming soon.",
        "dashboard_top_up_soon": "Top up (coming soon)",
        "dashboard_invite_friends": "Invite friends",
        "dashboard_invite_intro": "Share your registration link. The referral is recorded after your friend registers and connects WeChat.",
        "dashboard_my_invite_code": "My invite code",
        "dashboard_registration_link": "Registration link",
        "dashboard_copy_invite_code": "Copy code",
        "dashboard_copy_link": "Copy link",
        "dashboard_share_loading": "Preparing share text…",
        "dashboard_copy_share": "Copy share text",
        "dashboard_role_templates": "Custom role template management",
        "dashboard_role_templates_intro": "Create custom AI role templates and share them with friends or others.",
        "enter": "Enter",
        "dashboard_wechat_binding": "WeChat connection",
        "dashboard_unbind": "Disconnect",
        "dashboard_binding_status": "Connection status",
        "dashboard_checking": "Checking…",
        "dashboard_last_active": "Last active",
        "dashboard_unbind_confirm_title": "Disconnect WeChat?",
        "dashboard_unbind_warning": "The AI will stop replying on WeChat.\nMemories, conversations, and AI settings will be permanently deleted and cannot be restored.",
        "dashboard_unbind_confirm": "Confirm disconnect",
        "dashboard_more_soon": "More features, including history and notification settings, are coming soon.",
        "dashboard_share_text": "I'm using 朝夕相伴. Use my invite code {code} to try your own AI companion on WeChat: {link}",
        "dashboard_invite_count": "{count} invited",
        "dashboard_invite_code_copied": "Invite code copied",
        "dashboard_link_copied": "Registration link copied",
        "dashboard_share_copied": "Share text copied",
        "dashboard_bound": "✓ Connected",
        "dashboard_unbound": "Not connected",
        "processing": "Processing…",
        "creator_page_title": "Role Template Links — 朝夕相伴",
        "creator_heading": "Role template links",
        "creator_intro": "Set the role's name, personality, mission, and opening line. Approval generates a short summary; publication creates a shareable registration link.",
        "creator_new": "New role template",
        "creator_edit": "Edit role template",
        "creator_name": "Name",
        "creator_name_placeholder": "For example: Mia",
        "creator_personality": "Personality",
        "creator_personality_placeholder": "Describe how this AI sees the world, relates to people, communicates, and observes boundaries.",
        "creator_mission": "Mission",
        "creator_mission_placeholder": "Describe what it hopes to bring users over time. No numeric target is needed.",
        "creator_opening_line": "Opening line",
        "creator_opening_line_placeholder": "What the role says first after the user shares their preferred name.",
        "creator_public_summary": "Short summary",
        "creator_summary_edit_label": "Edit the short summary (one submission only)",
        "creator_summary_edit_note": "The summary must include the role name. An approval or rejection uses this version's edit; service errors do not.",
        "creator_summary_submit": "Submit summary edit",
        "creator_summary_reviewing": "The short summary is under review. Refresh later.",
        "creator_summary_required": "Enter a short summary.",
        "creator_summary_submitting": "Reviewing…",
        "creator_summary_success": "Updated successfully",
        "creator_submit": "Submit for review",
        "creator_unnamed": "Unnamed template",
        "creator_unknown_status": "Unknown status",
        "creator_used_count": "Used {count} times",
        "creator_latest_review": "Latest review",
        "creator_review_reason": "Review reason",
        "creator_activated_at": "First activated",
        "creator_expires_at": "Valid until",
        "creator_version_note": "The current link still uses published v{published}. The v{latest} shown above takes effect only after approval and publication.",
        "creator_edit_content": "Edit template",
        "creator_retry_review": "Retry review",
        "creator_publish_version": "Publish this version",
        "creator_disable_link": "Disable link",
        "creator_enable_link": "Enable link",
        "creator_copy_link": "Copy registration link",
        "creator_view_stats": "View stats",
        "creator_delete": "Delete",
        "creator_empty": "You have no role templates yet. You can have up to 3 active templates.",
        "creator_submitting": "Submitting…",
        "creator_submitted": "Submitted and this review attempt is complete.",
        "creator_action_success": "Done.",
        "creator_publish_success": "Published. The 360-day validity period starts at first activation.",
        "creator_delete_confirm": "Delete role template “{name}”? Its link will stop working immediately and cannot be restored.",
        "creator_deleted": "Template deleted.",
        "creator_link_copied": "Registration link copied.",
        "creator_stats_loading": "Loading stats…",
        "creator_stats_heading": "Funnel for the last 14 Beijing calendar days",
        "creator_stats_pv": "Views (PV)",
        "creator_stats_uv": "Visitors (UV)",
        "creator_stats_registered": "Registered",
        "creator_stats_scanned": "Scanned",
        "creator_stats_activated": "Activated",
        "creator_stats_completed": "Onboarding completed",
        "onboarding_page_title": "Connect WeChat — 朝夕相伴",
        "onboarding_back_admin": "Back to operations",
        "onboarding_register": "Register with phone",
        "onboarding_invite_code": "Invite code",
        "onboarding_optional": "Optional",
        "onboarding_verify_register": "Verify and register",
        "onboarding_resend": "Resend",
        "onboarding_scan_login": "Connect WeChat",
        "onboarding_refresh": "Refresh status",
        "onboarding_connected": "✅ WeChat connected! Send the AI a message in WeChat now to activate the conversation.",
        "onboarding_scan_caption": "Scan with the WeChat account you want to connect to AI4ALL.",
        "onboarding_qr_hint": "On mobile, press and hold the QR code and choose the option to scan it.",
        "onboarding_status": "Status",
        "onboarding_expires": "Expires",
        "onboarding_manual_command": "Fallback debug command",
        "onboarding_qr_missing": "No QR code was returned. Check the status or use the fallback debug command.",
        "onboarding_current_object": "Current records",
        "onboarding_otp_sent": "Verification code sent",
        "onboarding_invite_valid": "Invite code is valid",
        "onboarding_verified_qr": "Verified. Creating a QR code…",
        "onboarding_registering": "Registering…",
        "onboarding_registered": "Registration complete",
        "onboarding_binding_created": "Starting OpenClaw QR sign-in",
        "onboarding_binding_qr": "QR code ready. Waiting for scan",
        "onboarding_binding_completed": "Connected. Future messages will go to this account",
        "refreshing": "Refreshing…",
        "faq_page_title": "FAQ - 朝夕相伴",
        "faq_heading": "Frequently asked questions",
    },
    "ja-JP": {
        "page_brand": "朝夕相伴",
        "beta_label": "ベータ版",
        "nav_home": "ホーム",
        "nav_faq": "よくある質問",
        "nav_dashboard": "ユーザーセンター",
        "nav_back_dashboard": "ユーザーセンターに戻る",
        "logout": "ログアウト",
        "loading": "読み込み中…",
        "cancel": "キャンセル",
        "home_page_title": "朝夕相伴 — WeChat専用AIコンパニオン",
        "home_beta_stage": "現在、限定ベータテスト中です",
        "home_tagline": "あなた専用のWeChat AIコンパニオン\n会話、リマインダー、日々の記録をサポート",
        "home_subtitle": "電話番号認証 · WeChat連携 · すぐに利用可能\nユーザーごとに独立した、あなただけのAI",
        "home_login_title": "電話番号で登録 / ログイン",
        "home_mobile_qr_note": "スマートフォンではQRコードを長押しするか、スクリーンショットを保存してWeChatから読み取ってください。",
        "phone_label": "電話番号",
        "phone_placeholder": "電話番号を入力",
        "otp_label": "認証コード",
        "otp_placeholder": "6桁の認証コード",
        "get_otp": "認証コードを取得",
        "get_otp_countdown": "再取得 ({seconds}秒)",
        "resend_otp": "再送信",
        "verify_continue": "認証して続ける",
        "qr_alt": "WeChat連携用QRコード",
        "qr_scan_caption": "連携するWeChatアカウントでQRコードを読み取ってください",
        "qr_waiting": "読み取り待ち…",
        "login_redirecting": "ログインしました。移動しています…",
        "enter_dashboard": "ユーザーセンターへ",
        "invite_code_applied": "招待コードを適用しました：{code}",
        "role_will_create": "作成するキャラクター：{name}",
        "role_default_name": "朝夕パートナー",
        "role_personality_preview": "性格 / 雰囲気：{value}",
        "role_mission_preview": "使命：{value}",
        "role_summary_preview": "紹介：{value}",
        "role_expiry_preview": "テンプレート有効期限：{value}",
        "bind_wechat_title": "WeChatを連携",
        "session_binding_qr_loading": "ログイン済みです。WeChat連携用QRコードを作成しています…",
        "sending": "送信中…",
        "otp_sent_to": "{phone} に認証コードを送信しました",
        "verifying": "認証中…",
        "logging_in": "ログイン中…",
        "qr_generating": "QRコードを作成中…",
        "binding_success": "連携しました ✓",
        "dashboard_page_title": "ユーザーセンター — 朝夕相伴",
        "dashboard_my_account": "マイアカウント",
        "dashboard_account_id": "Account ID",
        "dashboard_plan": "プラン",
        "dashboard_registered_at": "登録日時",
        "dashboard_wallet": "貝殻残高",
        "dashboard_shells": "貝殻",
        "dashboard_wallet_note": "ベータ期間中は貝殻をプレゼントします。チャージプランは近日公開予定です。",
        "dashboard_top_up_soon": "チャージ（近日公開）",
        "dashboard_invite_friends": "友だちを招待",
        "dashboard_invite_intro": "専用登録リンクを友だちに共有してください。友だちが登録してWeChatを連携すると、招待関係が自動で記録されます。",
        "dashboard_my_invite_code": "招待コード",
        "dashboard_registration_link": "登録リンク",
        "dashboard_copy_invite_code": "コードをコピー",
        "dashboard_copy_link": "リンクをコピー",
        "dashboard_share_loading": "共有文を作成中…",
        "dashboard_copy_share": "共有文をコピー",
        "dashboard_role_templates": "カスタムキャラクターテンプレート管理",
        "dashboard_role_templates_intro": "AIキャラクターテンプレートを自由に作成し、友だちや他の人に共有できます。",
        "enter": "開く",
        "dashboard_wechat_binding": "WeChat連携",
        "dashboard_unbind": "連携解除",
        "dashboard_binding_status": "連携状態",
        "dashboard_checking": "確認中…",
        "dashboard_last_active": "最終アクティブ",
        "dashboard_unbind_confirm_title": "連携を解除しますか？",
        "dashboard_unbind_warning": "解除すると、AIはWeChatへの返信を停止します。\n記憶、会話履歴、AI設定は完全に削除され、復元できません。",
        "dashboard_unbind_confirm": "連携解除を確定",
        "dashboard_more_soon": "履歴や通知設定などの機能は近日公開予定です。",
        "dashboard_share_text": "朝夕相伴を使っています。招待コード {code} で、WeChat専用AIコンパニオンを体験してください：{link}",
        "dashboard_invite_count": "{count}人を招待済み",
        "dashboard_invite_code_copied": "招待コードをコピーしました",
        "dashboard_link_copied": "登録リンクをコピーしました",
        "dashboard_share_copied": "共有文をコピーしました",
        "dashboard_bound": "✓ 連携済み",
        "dashboard_unbound": "未連携",
        "processing": "処理中…",
        "creator_page_title": "キャラクターテンプレートリンク — 朝夕相伴",
        "creator_heading": "キャラクターテンプレートリンク",
        "creator_intro": "名前、性格、使命、最初のメッセージを設定します。審査通過後に短い紹介文が生成され、公開すると登録リンクを共有できます。",
        "creator_new": "テンプレートを新規作成",
        "creator_edit": "テンプレートを編集",
        "creator_name": "名前",
        "creator_name_placeholder": "例：小春",
        "creator_personality": "性格 / 雰囲気",
        "creator_personality_placeholder": "このAIの世界観、人との接し方、表現スタイル、境界線を説明してください。",
        "creator_mission": "使命",
        "creator_mission_placeholder": "長期的にユーザーへ届けたいものを説明してください。数値目標は不要です。",
        "creator_opening_line": "最初のメッセージ",
        "creator_opening_line_placeholder": "ユーザーの呼び名を聞いた後、キャラクターが最初に伝える言葉です。",
        "creator_public_summary": "ひとこと紹介",
        "creator_summary_edit_label": "ひとこと紹介を編集（正式な送信は1回のみ）",
        "creator_summary_edit_note": "紹介文にはキャラクター名が必要です。承認または拒否で編集機会を消費しますが、サービス障害時は消費しません。",
        "creator_summary_submit": "紹介文の変更を送信",
        "creator_summary_reviewing": "ひとこと紹介を審査中です。しばらくしてから更新してください。",
        "creator_summary_required": "ひとこと紹介を入力してください。",
        "creator_summary_submitting": "審査中…",
        "creator_summary_success": "変更しました",
        "creator_submit": "審査に提出",
        "creator_unnamed": "名称未設定",
        "creator_unknown_status": "状態不明",
        "creator_used_count": "{count}回利用済み",
        "creator_latest_review": "最新の審査",
        "creator_review_reason": "審査理由",
        "creator_activated_at": "初回有効化",
        "creator_expires_at": "有効期限",
        "creator_version_note": "現在の登録リンクは公開済みv{published}を使用しています。上記のv{latest}は審査通過後に公開すると反映されます。",
        "creator_edit_content": "内容を編集",
        "creator_retry_review": "再審査",
        "creator_publish_version": "この版を公開",
        "creator_disable_link": "リンクを無効化",
        "creator_enable_link": "リンクを再開",
        "creator_copy_link": "登録リンクをコピー",
        "creator_view_stats": "統計を見る",
        "creator_delete": "削除",
        "creator_empty": "テンプレートはまだありません。有効なテンプレートは最大3件まで所有できます。",
        "creator_submitting": "審査に提出中…",
        "creator_submitted": "提出し、今回の審査処理が完了しました。",
        "creator_action_success": "操作が完了しました。",
        "creator_publish_success": "公開しました。有効期間360日は初回有効化時から始まります。",
        "creator_delete_confirm": "テンプレート「{name}」を削除しますか？リンクは直ちに無効となり、復元できません。",
        "creator_deleted": "テンプレートを削除しました。",
        "creator_link_copied": "登録リンクをコピーしました。",
        "creator_stats_loading": "統計を読み込み中…",
        "creator_stats_heading": "直近14北京暦日のファネル",
        "creator_stats_pv": "表示 PV",
        "creator_stats_uv": "訪問者 UV",
        "creator_stats_registered": "登録",
        "creator_stats_scanned": "スキャン",
        "creator_stats_activated": "有効化",
        "creator_stats_completed": "オンボーディング完了",
        "onboarding_page_title": "WeChat連携 — 朝夕相伴",
        "onboarding_back_admin": "運営画面に戻る",
        "onboarding_register": "電話番号で登録",
        "onboarding_invite_code": "招待コード",
        "onboarding_optional": "任意",
        "onboarding_verify_register": "認証して登録",
        "onboarding_resend": "再送信",
        "onboarding_scan_login": "WeChatを連携",
        "onboarding_refresh": "状態を更新",
        "onboarding_connected": "✅ WeChatを連携しました。今すぐWeChatからAIにメッセージを送り、会話を有効化してください。",
        "onboarding_scan_caption": "AI4ALLに接続するWeChatアカウントで読み取ってください。",
        "onboarding_qr_hint": "スマートフォンではQRコードを長押しし、画像内のQRコードを読み取る項目を選んでください。",
        "onboarding_status": "状態",
        "onboarding_expires": "有効期限",
        "onboarding_manual_command": "デバッグ用フォールバックコマンド",
        "onboarding_qr_missing": "QRコードが返されていません。状態を確認するか、デバッグ用コマンドで調査してください。",
        "onboarding_current_object": "現在の対象",
        "onboarding_otp_sent": "認証コードを送信しました",
        "onboarding_invite_valid": "招待コードは有効です",
        "onboarding_verified_qr": "認証しました。QRコードを作成中…",
        "onboarding_registering": "登録中…",
        "onboarding_registered": "登録しました",
        "onboarding_binding_created": "OpenClaw QRログインを開始中",
        "onboarding_binding_qr": "QRコードを生成しました。読み取り待ちです",
        "onboarding_binding_completed": "連携完了。今後のメッセージはこのアカウントに届きます",
        "refreshing": "更新中…",
        "faq_page_title": "よくある質問 - 朝夕相伴",
        "faq_heading": "よくある質問",
    },
}


_FAQ_GROUPS: Dict[str, List[dict]] = {
    "zh-CN": [
        {"category": "产品&初心", "items": [
            {"question": "朝夕相伴 产品的初心是什么?", "answer": "随时随地的高质量陪伴，是我们常被忽视、却又最为奢侈的愿望。在今天，AI（人造智能）的进步让这个愿望成为可能。「朝夕相伴」致力融合科技进步和人文关怀，打造下个时代的个人陪伴体验。"},
            {"question": "朝夕相伴是什么？", "answer": "目前来说，朝夕相伴是一个接入微信的个人 AI 陪伴服务。ta可以陪你聊天、记住重要偏好、帮你做日常提醒"},
        ]},
        {"category": "接入&使用", "items": [
            {"question": "怎么接入我的微信？", "answer": "在首页完成手机号验证后，用需要接入的微信号扫码。扫码成功后，你的微信会和专属 AI 账号绑定。完成绑定后，请主动发一条消息给这个微信AI好友，完成激活"},
            {"question": "接入后，为什么看到的是微信ClawBot 和一个红色头像？", "answer": "我们目前是通过微信ClawBot的插件方式接入的，我们暂时不能帮你修改微信内的AI账号名称和头像，需要辛苦你手动操作"},
            {"question": "绑定后在哪里管理账号？", "answer": "可以从首页或顶部导航进入用户中心，查看绑定状态、余额和解绑入口。"},
            {"question": "需要充值&付费吗？", "answer": "我们会一直提供免费套餐服务，支持大约每天50条的纯文字聊天消息。后续也会推出VIP套餐，支持更多聊天容量和附加能力。同时，我们会有推荐新用户送贝壳的机制，即使免费套餐也能获得更多聊天容量。"},
            {"question": "底层用的什么基座模型？ 我可以自己选择吗？", "answer": "目前使用的是DeepSeek V4模型，如果有国产更好的模型，我们也会持续评估接入。目前不支持用户自己选择基座模型，未来有可能增加高级设置，预期都会是国产模型"},
        ]},
        {"category": "隐私&记忆", "items": [
            {"question": "每个微信账号的数据会互相影响吗？", "answer": "不会。每个账号都有独立的 Soul、对话状态和记忆。项目里的核心不变量就是按账号隔离。"},
            {"question": "AI 会记住我说过的所有话吗？", "answer": "不会把每句话都长期保存成记忆。系统会在对话后提炼更稳定、对陪伴有帮助的信息；短期上下文和长期记忆是分开的。"},
            {"question": "解绑后会发生什么？", "answer": "解绑后 AI 会停止响应这个微信号,清除历史数据和记忆，就像AI进入下一个轮回"},
        ]},
        {"category": "能力边界", "items": [
            {"question": "朝夕相伴是客服机器人吗？", "answer": "不是。ta定位为个人 AI 陪伴，更像一个长期相处的，聊得来的好朋友，而不是标准问答式客服。"},
            {"question": "ta可以接收图片和视频吗？", "answer": "接收&理解图片的功能已经上线，视频还没确定要不要支持，因为预期消耗token等资源较多，正在讨论中"},
            {"question": "ta可以进行搜索吗？了解最新新闻吗？", "answer": "ta具备查询搜索引擎的能力，但有时候不一定能第一时间去做，ta还沉浸在聊天的氛围中，你可以明确说，帮我搜索一下「我是歌手最新一期的排名」"},
            {"question": "ta能代替医生、律师或心理咨询师吗？", "answer": "不能。ta可以提供一般信息和陪伴，但不能做医疗诊断、法律结论或专业心理治疗。高风险事项请咨询专业人士。"},
        ]},
    ],
    "en-US": [
        {"category": "Product & purpose", "items": [
            {"question": "Why was 朝夕相伴 created?", "answer": "High-quality companionship anytime and anywhere is an often overlooked yet precious wish. Advances in AI now make it possible. 朝夕相伴 brings technology and human care together to create a new kind of personal companionship."},
            {"question": "What is 朝夕相伴?", "answer": "朝夕相伴 is a personal AI companion connected through WeChat. It can chat with you, remember important preferences, and help with everyday reminders."},
        ]},
        {"category": "Setup & use", "items": [
            {"question": "How do I connect my WeChat?", "answer": "Verify your phone number on the home page, then scan the QR code with the WeChat account you want to connect. After it is connected, send the AI contact a message in WeChat to activate it."},
            {"question": "Why do I see WeChat ClawBot and a red avatar after connecting?", "answer": "We currently connect through the WeChat ClawBot plugin. We cannot yet change the AI account name or avatar inside WeChat for you, so please update them manually."},
            {"question": "Where can I manage my account after connecting?", "answer": "Open the Account Center from the home page or top navigation to view connection status, balance, and the disconnect option."},
            {"question": "Do I need to pay?", "answer": "We will continue to offer a free plan supporting about 50 text messages per day. VIP plans with more capacity and features are planned. Referrals can also earn shells for additional chat capacity."},
            {"question": "Which foundation model is used? Can I choose one?", "answer": "The service currently uses DeepSeek V4. We will continue evaluating stronger domestic models. Users cannot choose the foundation model yet; advanced settings may be added later."},
        ]},
        {"category": "Privacy & memory", "items": [
            {"question": "Can data from different WeChat accounts affect each other?", "answer": "No. Every account has its own Soul, conversation state, and memory. Account-level isolation is a core system invariant."},
            {"question": "Does the AI remember everything I say?", "answer": "No. Not every message becomes a long-term memory. The system extracts stable information that helps companionship, while short-term context and long-term memory remain separate."},
            {"question": "What happens when I disconnect?", "answer": "The AI stops responding to that WeChat account, and its conversation history and memories are deleted permanently."},
        ]},
        {"category": "Capability boundaries", "items": [
            {"question": "Is 朝夕相伴 a customer-service bot?", "answer": "No. It is a personal AI companion, closer to a long-term friend you enjoy talking with than a standard question-and-answer bot."},
            {"question": "Can it receive images and videos?", "answer": "Image understanding is available. Video support is still under discussion because it is expected to consume substantially more resources."},
            {"question": "Can it search and understand current news?", "answer": "It can use a search engine, though it may not always search immediately during a conversation. You can ask explicitly, for example, to search for the latest results of a show."},
            {"question": "Can it replace a doctor, lawyer, or therapist?", "answer": "No. It can provide general information and companionship, but not medical diagnoses, legal conclusions, or professional therapy. Consult a qualified professional for high-risk matters."},
        ]},
    ],
    "ja-JP": [
        {"category": "製品と理念", "items": [
            {"question": "朝夕相伴はなぜ作られたのですか？", "answer": "いつでもどこでも質の高い寄り添いを得ることは、見過ごされがちでありながら、とても大切な願いです。AIの進歩によって、その願いが実現可能になりました。朝夕相伴は技術と人への思いやりを融合し、次の時代の個人的な寄り添い体験を目指します。"},
            {"question": "朝夕相伴とは何ですか？", "answer": "朝夕相伴はWeChatにつながる個人向けAIコンパニオンです。会話をしたり、大切な好みを覚えたり、日々のリマインダーを手伝ったりできます。"},
        ]},
        {"category": "接続と利用", "items": [
            {"question": "WeChatに接続するには？", "answer": "ホームで電話番号を認証し、接続したいWeChatアカウントでQRコードを読み取ります。接続後、WeChatのAI連絡先へメッセージを1通送り、有効化してください。"},
            {"question": "接続後にWeChat ClawBotと赤いアイコンが表示されるのはなぜですか？", "answer": "現在はWeChat ClawBotプラグインを通じて接続しています。WeChat内のAIアカウント名とアイコンはまだこちらで変更できないため、手動で設定してください。"},
            {"question": "接続後、アカウントはどこで管理できますか？", "answer": "ホームまたは上部ナビゲーションからユーザーセンターを開き、接続状態、残高、連携解除を確認できます。"},
            {"question": "料金はかかりますか？", "answer": "1日約50件のテキストメッセージに対応する無料プランを継続して提供します。より多くの容量や機能を備えたVIPプランも予定しています。紹介によって貝殻を獲得し、無料プランでも会話容量を増やせます。"},
            {"question": "どの基盤モデルを使っていますか？選べますか？", "answer": "現在はDeepSeek V4を使用しています。より優れた国内モデルも継続して評価します。現時点ではモデルを選択できませんが、将来は詳細設定を追加する可能性があります。"},
        ]},
        {"category": "プライバシーと記憶", "items": [
            {"question": "WeChatアカウント間でデータが影響し合いますか？", "answer": "いいえ。各アカウントには独立したSoul、会話状態、記憶があります。アカウント単位の分離はシステムの中核原則です。"},
            {"question": "AIは話したことをすべて覚えますか？", "answer": "いいえ。すべての発言を長期記憶として保存するわけではありません。寄り添いに役立つ安定した情報を抽出し、短期コンテキストと長期記憶は分けて管理します。"},
            {"question": "連携を解除するとどうなりますか？", "answer": "AIはそのWeChatアカウントへの応答を停止し、会話履歴と記憶は完全に削除されます。"},
        ]},
        {"category": "できることと限界", "items": [
            {"question": "朝夕相伴はカスタマーサポートBotですか？", "answer": "いいえ。標準的なQ&A型Botではなく、長く付き合い、気軽に話せる友だちに近い個人向けAIコンパニオンです。"},
            {"question": "画像や動画を受け取れますか？", "answer": "画像の受信と理解には対応しています。動画は多くのリソース消費が見込まれるため、対応を検討中です。"},
            {"question": "検索や最新ニュースの確認はできますか？", "answer": "検索エンジンを利用できますが、会話の流れによってはすぐ検索しない場合があります。「最新の結果を検索して」のように明確に依頼できます。"},
            {"question": "医師、弁護士、心理士の代わりになりますか？", "answer": "なりません。一般的な情報や寄り添いは提供できますが、医療診断、法的判断、専門的な心理療法は行えません。重要な事項は専門家に相談してください。"},
        ]},
    ],
}


def web_ui_messages(
    *, app_id: str = ZHAOXI_APP_ID, language: Optional[str] = None
) -> Dict[str, str]:
    """返回公开 Web UI 的完整文案目录。"""

    resolved = language or product_default_language(app_id)
    catalog = _WEB_UI_MESSAGES.get(resolved) or _WEB_UI_MESSAGES["zh-CN"]
    return dict(catalog)


def faq_groups(
    *, app_id: str = ZHAOXI_APP_ID, language: Optional[str] = None
) -> List[dict]:
    """返回产品默认语言的 FAQ 内容；返回副本避免调用方修改全局目录。"""

    resolved = language or product_default_language(app_id)
    groups = _FAQ_GROUPS.get(resolved) or _FAQ_GROUPS["zh-CN"]
    return [
        {
            "category": group["category"],
            "items": [dict(item) for item in group["items"]],
        }
        for group in groups
    ]


__all__ = ["faq_groups", "web_ui_messages"]
